### ISSUE TITLE
Spacing Ratio

### ISSUE THREAD

**Issue by rik030** [Kaiseem/DAR-UNet#3]
Dear Sir,
How to achieve the spacing ratio  [1, 1, 4] in the semantic segmentation part?

**Comment by Kaiseem** [comment]
Hi，if your data is saved as the format of nii.gz, you can get the spacing by python library SimpleITK, function GetSpacing, like the following code:

obj=SimpleITK.ReadImage(path)
print(obj.GetSpacing())

Then you can know the spacing of the data.
In order to spacing normalize the data to the spacing ratio [1, 1, 4], I recommend finding some existing libraries, e.g., [Monai](https://github.com/Project-MONAI/MONAI).
